olw4484/10Team_NetWork

Assets/00_WorkSpace/NormalSeed/Scenes/MovementTest.unity
Assets/00_WorkSpace/NormalSeed/Scripts/CameraController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/CameraController.cs.meta
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

Y키 토글로 카메라를 플레이어 위치에 고정 / 고정 해제 하는 기능
스페이스바를 누르고 있으면 카메라를 플레이어 위치에 고정하는 기능
화면 경계선에 마우스를 가져다 대면 카메라를 해당 방향으로 이동시키는 기능
마우스 스크롤을 통해 카메라 시야각을 조절해 줌인/ 줌아웃 하는 기능 구현

[Feat] Camera Controller

---

Assets/00_WorkSpace/NormalSeed/Scenes/MovementTest.unity
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroMovement.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Hero1SkillSet.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/SkillSO.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/SkillSet.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Test.meta
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Test/TestSkillManager.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Test/TestSkillManager.cs.meta
Assets/ExternalDependencyManager/Editor/1.2.186/Google.IOSResolver.dll.meta
Assets/ExternalDependencyManager/Editor/1.2.186/Google.JarResolver.dll.meta
Assets/ExternalDependencyManager/Editor/1.2.186/Google.PackageManagerResolver.dll.meta
Assets/ExternalDependencyManager/Editor/1.2.186/Google.VersionHandlerImpl.dll.meta
Assets/ExternalDependencyManager/Editor/CHANGELOG.md.meta
Assets/ExternalDependencyManager/Editor/Google.VersionHandler.dll.meta
Assets/ExternalDependencyManager/Editor/LICENSE.meta
Assets/ExternalDependencyManager/Editor/README.md.meta
Assets/ExternalDependencyManager/Editor/external-dependency-manager_version-1.2.186_manifest.txt.meta
Assets/Firebase/Editor/Firebase.Editor.dll.meta

근접공격 영웅인 Hero1의 Q, W스킬 기본기능 구현
Q : 부채꼴 범위 공격 스킬
W : 방어력 버프 스킬
수정사항
HeroMovement : dir이 Vector.zero일 때 나타는 오류 로그를 안보이게 하기 위해서 조건 추가
SkillSet : mainCam에 메인 카메라 지정

LGH/Hero1 SkillSet

---

Assets/00_WorkSpace/NormalSeed/Scenes/MovementTest.unity
Assets/00_WorkSpace/NormalSeed/Scripts/CameraController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroModel.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroMovement.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Hero1SkillSet.cs
ProjectSettings/TagManager.asset

카메라 네트워킹
- PhotonView를 이용해 IsMine인 플레이어를 찾아 참조해오도록 변경
Hero Attack
영웅의 기본 공격 기능 구현
→ 공격 사정거리 안에 있는 적을 우클릭시 기본공격 실행
→ 공격 사정거리 밖에 있을 시에는 사정거리 안에 들어오도록 이동한 뒤 사정거리 안에 들어오면 공격

LGH/Camera Network, Hero Attack

---

Assets/00_WorkSpace/DevIRU0413/Scripts.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Interface.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Interface/ILoadingUI.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Interface/ILoadingUI.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_IPoolable.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_IPoolable.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_Pool.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_Pool.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_PoolManager.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_PoolManager.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_SpawnObjectLifeCycle.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_SpawnObjectLifeCycle.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/YSJ_SimpleSingleton.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/YSJ_SimpleSingleton.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/YSJ_GameManager.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/YSJ_GameManager.cs.meta

- 범용 풀링 시스템 구축:
- `YSJ_PoolManager`: 풀 관리 싱글톤 매니저
- `YSJ_Pool`: 단일 풀 객체
- `YSJ_IPoolable`: 풀링 대상 오브젝트 인터페이스
- `YSJ_SpawnObjectLifeCycle`: 풀링 오브젝트의 수명 주기 자동 관리
---
- 풀 생성 (`CreatePool`)
- 객체 생성 및 반환 (`Spawn`, `Despawn`)
- Key 기반 풀 추적 및 정합성 검사
- GameObject를 내부 Stack으로 관리
- `YSJ_IPoolable`을 통해 spawn/despawn 이벤트 전파
- `OnSpawned()`, `OnDespawned()` 인터페이스 제공
- Unity 이벤트 연결 및 상태 초기화 등에 활용 가능
- 풀링된 오브젝트에 부착하여 `OnEnable` 기준 수명 타이머 작동
- 수명이 다하면 `Despawn()` 또는 `Destroy()` 수행
- 외부에서 수명시간 설정 가능 (`SetLifeTime()`)

[Feat] Pooling System 구현

---

Assets/00_WorkSpace/JangHyeonTae/Resources/PopUpCanvas.prefab
Assets/00_WorkSpace/JangHyeonTae/Resources/PopUpUI/BlueFullText.prefab
Assets/00_WorkSpace/JangHyeonTae/Resources/PopUpUI/RedFullText.prefab
Assets/00_WorkSpace/JangHyeonTae/Scenes/JHT_Lobby.unity
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_TeamManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_UIManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/JHT_BlueFullPanel.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/JHT_RedFullPanel.cs

[Feat] Panel UI for other programer

---

Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/PopUp/JHT_BlueFullPanel.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/PopUp/JHT_RedFullPanel.cs

[Refactor] popup refactor

---

Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/BrutalSmite.asset
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Harden.asset
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Hero1SkillSet.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

Hero1의 R스킬인 Brutal Smite 네트워크 동기화 작업

[Fix] Hero1 R Skill Networking

---

Assets/00_WorkSpace/DevIRU0413/Scripts/UI/YSJ_UIBinder.cs.meta
Assets/00_WorkSpace/NormalSeed/Prefabs.meta
Assets/00_WorkSpace/NormalSeed/Prefabs/GameManager.prefab
Assets/00_WorkSpace/NormalSeed/Prefabs/GameManager.prefab.meta
Assets/00_WorkSpace/NormalSeed/Prefabs/SkillManger.prefab
Assets/00_WorkSpace/NormalSeed/Prefabs/SkillManger.prefab.meta
Assets/00_WorkSpace/NormalSeed/Scenes/MovementTest.unity
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroMovement.cs

[Chore] Refactoring, Prefab

---

Assets/00_WorkSpace/NormalSeed/Resources/Hero1.prefab
Assets/00_WorkSpace/NormalSeed/Scenes/MovementTest.unity
Assets/00_WorkSpace/NormalSeed/Scripts/CameraController.cs

Hero Instantiate시 카메라 각도 조절 추가

[Fix] Camera Rotation Init

---

Assets/00_WorkSpace/NormalSeed/Resources/Hero1.prefab

Hero Prefab 에 아이템 매니저와 최종 스탯 관리자 추가

[Fix] Hero Prefab

---

Assets/00_WorkSpace/JangHyeonTae/Scenes/JHT_Lobby.unity
Assets/00_WorkSpace/JangHyeonTae/Scriptable/1.asset
Assets/00_WorkSpace/JangHyeonTae/Scriptable/2.asset
Assets/00_WorkSpace/JangHyeonTae/Scriptable/3.asset
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_NetworkManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_RoomManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/NetworkPanel/JHT_NetworkUIPanel.cs

[Feat] setting

---

Assets/00_WorkSpace/Olw4484/Script/NetWork/KMS_NetWorkManager.cs
Assets/Prototype/Script/CommandPlayer/HQ/CommandPlayer.cs
Assets/Prototype/Script/CommandPlayer/Minion/MinionController.cs
Assets/Prototype/Script/CommandPlayer/ScriptableObject/WaypointGroupSO.cs
Assets/Resources/EliteMinion.prefab
Assets/Resources/HQ.prefab
Assets/Resources/MeleeMinion.prefab
Assets/Resources/RangedMinion.prefab

[Refactor] Overhaul minion waypoint movement logic

---

Assets/00_WorkSpace/coffeelatt/Scripts/SHI_Inventory.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_Inventory.cs.meta
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_InventorySlot.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_InventoryUi.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_InventoryUi.cs.meta
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_ItemManager.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_Itemcreate.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_ResultValue.cs

코드 오류때문에 임시로 연결되어있는 애땜에 스태틱 인스턴스만 살려놓음

[fix] 싱글톤해제

---

Assets/00_WorkSpace/JangHyeonTae/Scenes/JHT_Lobby.unity
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_NetworkManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_RoomManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_SceneManager.cs

[Feat] Change scene

---

Assets/00_WorkSpace/NormalSeed/Scripts/CameraController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs

GameManager에서 플레이어 등록 로직 변경
GameManager를 참조해올 수 있을 때까지 계속 탐색함

[Fix] HeroController register player

---

Assets/00_WorkSpace/DevIRU0413/Prefabs/SystemManager.prefab
Assets/00_WorkSpace/DevIRU0413/Prefabs/SystemManager.prefab.meta
Assets/00_WorkSpace/DevIRU0413/Prefabs/UIManager.prefab
Assets/00_WorkSpace/DevIRU0413/Prefabs/UIManager.prefab.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/Scene/InGameScene.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Scene/SceneBase.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/UI/Panel/View/LoginView.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/UI/YSJ_UISpawnFactory.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_Pool.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/Util/PoolTool/YSJ_PoolManager.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/YSJ_AudioManager.cs
Assets/00_WorkSpace/DevIRU0413/Scripts/YSJ_AudioManager.cs.meta
Assets/00_WorkSpace/DevIRU0413/Scripts/YSJ_UIManager.cs
Assets/00_WorkSpace/DevIRU0413/YSJ_TestScene 1.unity
Assets/00_WorkSpace/DevIRU0413/YSJ_TestScene 1.unity.meta
Assets/00_WorkSpace/DevIRU0413/YSJ_TestScene.unity
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/JHT_BaseUI.cs

UIManager, AudioManager, PoolManager를 포함한 주요 시스템 매니저 구조를 개선하고, 이를 기반으로 한 `SceneBase`, `InGameScene`, UI 시스템 관련 로직을 통합 리팩토링하였습니다.

System 구조 개선 및 관련 기능 통합

---

Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_NetworkManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_RoomManager.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/NetworkPanel/JHT_NetworkUIPanel.cs

Leaveroom진행시 버그 수정(아직 test 많이는 못해봐서 버그 발생해서 말해주시면 그부분 수정해보겠습니다)

[Fix] LeaveRoom Active

---

Assets/00_WorkSpace/JangHyeonTae/Scenes/JHT_Lobby.unity
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex0.asset
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex0.asset.meta
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex1.asset
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex1.asset.meta
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex2.asset
Assets/00_WorkSpace/JangHyeonTae/Scriptable/HeroIndex2.asset.meta
Assets/00_WorkSpace/JangHyeonTae/Scripts/UIBindin/NetworkPanel/JHT_NetworkUIPanel.cs

[Fix] NetworkManagerUI

---

Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_NetworkManager.cs

[Fix] NetworkManager 리소스 참조 불가 fix

[Fix] NetworkManager

---

Assets/00_WorkSpace/JangHyeonTae/Scripts/JHT_PlayerPanelItem.cs
Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_RoomManager.cs

[Fix] 룸에서 나갈경우 패널에 레디와 캐릭터 선택 이미지 초기화 안되는것 초기화 설정 완료

[Fix] RoomPanel Respawn

---

Assets/00_WorkSpace/coffeelatt/Prefabs/BuffImmortal.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/BuffLifeSteal.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/BuffSlayer.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/ExpPotion.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/HpPotion.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/MinionSlayer.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/MpPotion.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/RapidFirecannon.prefab
Assets/00_WorkSpace/coffeelatt/Prefabs/TrinityForce.prefab
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_Inventory.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_ItemGet.cs
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_ItemGet.cs.meta
Assets/00_WorkSpace/coffeelatt/Scripts/SHI_Spawner.cs

[feat]item get create

---

Assets/00_WorkSpace/NormalSeed/Animator/Hero1AnimatorControlelr.controller
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroMovement.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Hero1SkillSet.cs
Assets/00_WorkSpace/Olw4484/Script/Minion/KMS_MinionController.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Assets/Prototype/Script/CommandPlayer/HQ/HQ.cs
Assets/Prototype/Script/CommandPlayer/Interface/IDamageable.cs
ProjectSettings/ProjectSettings.asset

IDamageable에 RPC_TakeDamage 추가

[Fix] IDamageable fix

---

Assets/00_WorkSpace/DevIRU0413/Scripts/Scene/LobbyScene.cs.meta
Assets/Prototype/Scenes/Lobby.unity

로비 씬전화시 초기화 순서 로비씬 정리 및 사운드 데이터 매니저 넣기

[Feat] Set LobbyScene

---

Assets/00_WorkSpace/JangHyeonTae/Scripts/Manager/JHT_NetworkManager.cs
Assets/Prototype/Scenes/Lobby.unity

Add sceneBase for lobby

---

Assets/00_WorkSpace/NormalSeed/Scripts/DamageCalculate.cs
Assets/00_WorkSpace/NormalSeed/Scripts/DamageCalculate.cs.meta
Assets/00_WorkSpace/NormalSeed/Scripts/Hero/HeroController.cs
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Bash.asset
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/BladeWind.asset
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/BrutalSmite.asset
Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Hero1/Hero1SkillSet.cs

데미지 계산 공식
입히는 데미지 : 데미지량 * 100 / (100 + 대상의 방어력)
추가

[Feat] Damage Calculate

---

Assets/00_WorkSpace/NormalSeed/Scripts/Skills/Test/LGH_TestNetwork.cs

[Test] Seprate Test Network

---

Assets/Prototype/Script/CommandPlayer/HQ/HQ.cs

[Refactor] change logic
